### ISSUE TITLE
StateM DSL more_commands

### ISSUE THREAD

**Issue by adkron** [alfert/propcheck#107]
I would love to generate much larger command sequences when using the StateM DSL. I believe it would be more likely to find issues in longer command sequences for some instances.

**Comment by alfert** [comment]
The easiest way to do this is to set the `:max_size` attribute of the property: 
```elixir
property "many commands", [:verbose, max_size: 200] do
  forall cmds <- commands(__MODULE__) do
      (length(cmds) >= 0) 
      |> measure("cmds-list length", length cmds)
    end
end
```

The background ist that the `resize` function does not work properly with the recursive generators. Therefore the `:max_size` attribute is the upper bound. 

But it is a good idea to dig into this further. I assume a bug in proper (perhaps only in the docs).

**Comment by adkron** [comment]
Thanks for that!

**Comment by alfert** [comment]
I added  this issue https://github.com/proper-testing/proper/issues/192 in PropEr. Perhaps they find something, since their implementation of `more_commands/2` does not work as well (not surprisingly, since PropCheck delegates the work for `StateM` to their implementation).

**Comment by x4lldux** [comment]
Required changes were merged into PropEr.

**Comment by evnu** [comment]
@alfert Can this be closed?

**Comment by alfert** [comment]
I guess so, but I didn't tried it out.
