### ISSUE TITLE
Move counter-examples file to be configured via application configuration (config.exs)

### ISSUE THREAD

**Issue by sashaafm** [alfert/propcheck#115]
Hello Alfert, do you have plans or would it be possible to change `prop check` to have the counter-examples files be configure via the standard application configuration (`config.exs` files) instead of via the `Mixfile`?

To us this would be useful to allow running applications depending on `propcheck` on slave nodes via Erlang's `slave` APIs. The problem resides in the slaves receiving the code paths from the code server (Erlang's `code` module), but ignoring the counter-examples file inside the `_build` dir. By having the counter-examples file configured via the application configuration we believe the slave nodes would be able to access the file. We do this with other dependencies who needs files and allow these to be configured via `config.exs`.

Right now, our workaround is to set the `app: false` flag on `mix.exs` dependency declaration for `propcheck`, and manually start `propcheck` in the ExUnit helper file. This allows our property tests to run in the master node, and allows the slave nodes to start up and execute because `prop check` won't look for the counter-examples file.

Thank you for your time and consideration 🙏

**Comment by evnu** [comment]
@sashaafm would you be interested in implementing this after #122 is merged? That way, the new feature can be tested in your slave configuration without too much back and forth.
