### ISSUE TITLE
StateM DSL commands with state

### ISSUE THREAD

**Issue by x4lldux** [alfert/propcheck#131]
What's the rationale behind `commands/1` generating a tuples with state and a symbolic call? Am I missing something? Why not just a symbolic call like in regular `StateM`?
When PropEr is generating counter-examples, or when printing a "report" with `with_fail/2`  it gets very noisy, especially when state is big.

**Comment by alfert** [comment]
Good question. I need to dig into the code to come with a good answer. This may take some time, since I am quite busy at the moment. Please be patient.

**Comment by x4lldux** [comment]
If that helps, I have a branch with some changes that removes state form the list of generated commands. It looks as it works, but not knowing why it was introduced in the first place, I might have missed something. It introduces a semi breaking change, though: `run_commands` needs an additional argument with module implementing `&initial_state/0` (just like the regular StateM needs). I've added a 1 argument version to keep compatibility, which infers that module from the first generated command - but does not necessarily has to be in the same module as `&initial_sate/0` function.
See https://github.com/x4lldux/propcheck/tree/quieter_statem_dsl

**Comment by alfert** [comment]
I took a short look at the source. I agree that this looks like it is not really needed, since the only situation where it is used (in `execute_commands`), the parameter is ignored. I need to take a look at your implementation though.

**Comment by x4lldux** [comment]
Actually it's used in `run_commands` to get the initial state out of the first command, and also in `is_valid` to do the same. `is_valid` actually calls it a _first_state_ and compares it to _initial_state_ which gets from `mod.initial_state()` -- this comparison is what I don't understand the most, because it looks like a redundant check but often they are there because of some edge cases.
