### ISSUE TITLE
Using `PropCheck.TargetedPBT.exists/2` causes a crash

### ISSUE THREAD

**Issue by x4lldux** [alfert/propcheck#133]
The `PropCheck.TargetedPBT.exists/2` causes a crash when it returns false.
```Elixir
  property "`exist` crashes on false" do
    exists p <- false do
      p
    end
  end
```
crashes with:
```
  1) property `exist` crashes on false (PropCheck.Test.TargetPathTest)
     test/targeted_path_test.exs:65
     ** (CaseClauseError) no case clause matching: false
     code: property "`exist` crashes on false" do
     stacktrace:
       (propcheck) lib/properties.ex:190: PropCheck.Properties.handle_check_results/5
       test/targeted_path_test.exs:65: (test)
```

**Comment by evnu** [comment]
[From here](https://proper-testing.github.io/apidocs/) (highlighting mine):

> `?EXISTS(<Xs>, <Xs_type>, <Prop>)`
>   The ?EXISTS macro uses the targeted PBT component of PropEr to try to find one instance of <Xs> that makes the <Prop> true. If such a <Xs> is found the property  passes. **Note that there is no counterexample if no such <Xs> could be found.**

This should be easy to fix by extending `Properties.handle_check_results/5` with a catch-all clause.
