### ISSUE TITLE
Allow `property/1` to mark stub tests

### ISSUE THREAD

**Issue by evnu** [alfert/propcheck#135]
I sometimes use `test/1` with `ExUnit` to write down a test-to-be-implemented. For example:

```elixir
defmodule Test do
  use ExUnit.Case

  test "I don't know yet what to test here"
end
```

When executing the test, this fails with `not implemented`.

```
  1) test this test is not yet implemented (Test)
     test/test.exs:4
     Not implemented
```

I think this would be a useful addition to the `property` macro as well. Currently, this fails as there is no function `property/1`:

```elixir
defmodule Test do
  use ExUnit.Case
  use PropCheck

  property "this property is not yet implemented"
end
```

Error:

```
== Compilation error in file test/b_test.exs ==
** (CompileError) test/test.exs:5: undefined function property/1
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:237: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

**Comment by alfert** [comment]
I did not know about this feature of `test`, but I like very much and I always wanted to have something similar. So let's provide a similar feature for `property`  together with a nice documentation! 💚
