### ISSUE TITLE
Mechanism for constraining length of generated lists

### ISSUE THREAD

**Issue by TylerPachal** [alfert/propcheck#188]
Hello,

In `StreamData` the list (`list_of`) generator has some nice [options](https://hexdocs.pm/stream_data/StreamData.html#list_of/2-options) that allow you to specify the `:min_length,`:max_length`, or exact `:length` of a list.  Is there a way to achieve the same thing using PropCheck?

Example from their docs:
```
list_of(integer(), length: 3)
list_of(integer(), max_length: 1)
```

**Comment by evnu** [comment]
I think there isn't a helper for this, but it should be quite simple to do this yourself with `List.duplicate/2` and your generator of choice. Example iex session:

```
~u(master ✗) MIX_ENV=test iex -S mix run
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Compiling 1 file (.ex)
Interactive Elixir (1.11.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> use PropCheck
PropCheck.TargetedPBT
iex(2)> produce(List.duplicate(nat(), 5))
{:ok, [9, 6, 10, 1, 10]}
iex(3)> produce(List.duplicate(nat(), 5))
{:ok, [4, 7, 6, 9, 0]}
iex(4)> produce(List.duplicate(nat(), 5))
{:ok, [2, 7, 1, 3, 8]}
iex(5)> produce(List.duplicate(nat(), 5))
{:ok, [0, 10, 5, 6, 9]}
iex(6)> produce(List.duplicate(nat(), 5))
{:ok, [8, 3, 5, 4, 9]}
iex(7)> produce(List.duplicate(nat(), 5))
{:ok, [6, 0, 8, 8, 9]}
```

**Comment by TylerPachal** [comment]
@evnu Thanks!  I have never noticed `List.duplicate` before.  My requirements ended up changing a bit and I ended up writing a generator which produces unique lists instead:

```
def uniq_list(gen) do
  sized(
    size,
    uniq_list(list_length(size), MapSet.new(), gen)
  )
end

# If we don't introduce some randomness then the list length will always be
# the same as the generation size.
defp list_length(generation_size) do
  Enum.random(0..generation_size)
end

defp uniq_list(0, acc, _gen) do
  MapSet.to_list(acc)
end
defp uniq_list(max, acc, gen) do
  let val <- gen do
    if MapSet.member?(acc, val) do
      uniq_list(max, acc, gen)
    else
      uniq_list(max - 1, MapSet.put(acc, val), gen)
    end
  end
end
```

**Comment by kostis** [comment]
I just noticed this issue.  If it is of any help, note that PropEr has a `vector` built-in generator, for generating a list of exact length.

**Comment by evnu** [comment]
@kostis you are right, `PropCheck` also delegates to that (see [here](https://github.com/alfert/propcheck/blob/master/lib/basic_types.ex#L132)). With that, constructing a list with a minimum and maximum length should be quite simple:

```elixir
def gen_list(gen, args) do
  min_length = args[:min_length] || 0
  max_length = args[:max_length] || :inf
  let vector_length <- integer(min_length, max_length) do
    vector(vector_length, gen)
  end
end
```
