### ISSUE TITLE
Counter-Example is empty when test failed

### ISSUE THREAD

**Issue by ray-sh** [alfert/propcheck#208]
Counter-Example output is empty.
I am expecting it return since there is a bug in the function biggest

mix test
..

  1) property biggest num test (PbtTest)
     test/pbt_test.exs:10
     Property Elixir.PbtTest.property biggest num test() failed. Counter-Example is:

     Counter example stored.

     code: nil
     stacktrace:
       (propcheck 1.4.0) lib/properties.ex:227: PropCheck.Properties.handle_check_results/2
       test/pbt_test.exs:10: (test)

Finished in 0.1 seconds (0.00s async, 0.1s sync)
1 doctest, 1 property, 1 test, 1 failure

`
defmodule PbtTest do
  use ExUnit.Case
  doctest Pbt
  use PropCheck

  test "greets the world" do
    assert Pbt.hello() == :world
  end

  property "biggest num test" do
    forall(type <- :proper_types.list(:proper_types.integer())) do
      biggest(type) == List.last(Enum.sort(type))
    end
  end

  def biggest([head | tail]) do
    biggest(tail, head)
  end

  defp biggest([], max) do
    max
  end

  defp biggest([head | tail], max) when head > max do
    biggest(tail, head)
  end

  defp biggest([head | tail], max) when head < max do
    biggest(tail, max)
  end
end

`
elixir -v
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit] [dtrace]

Elixir 1.12.1 (compiled with Erlang/OTP 24)

 {:propcheck, "~> 1.4", only: [:test, :dev]}

**Comment by evnu** [comment]
Running with `PROPCHECK_VERBOSE`:

```
PROPCHECK_VERBOSE=1 mix test
!
Failed: After 1 test(s).
An exception was raised:
** (FunctionClauseError) no function clause matching in BlaTest.biggest/1
Stacktrace:
    test/bla_test.exs:11: BlaTest.biggest([])
    test/bla_test.exs:7: anonymous fn/4 in BlaTest."property biggest num test"/1

[]

Shrinking (0 time(s))
[]


  1) property biggest num test (BlaTest)
     test/bla_test.exs:5
     Property Elixir.BlaTest.property biggest num test() failed. Counter-Example is:


     Counter example stored.

     code: nil
     stacktrace:
       (propcheck 1.4.0) lib/properties.ex:227: PropCheck.Properties.handle_check_results/2
       test/bla_test.exs:5: (test)
```

**Comment by evnu** [comment]
The counter example is `[]`. As far as I can tell, the counter example is stored, as the second run of `mix test` results in the counter example being exercised again:

```
/tmp/bla rm _build/propcheck.ctex; mix test; mix test
==> propcheck
Compiling 1 file (.ex)
==> bla


  1) property biggest num test (BlaTest)
     test/bla_test.exs:5
     Property Elixir.BlaTest.property biggest num test() failed. Counter-Example is:


     Counter example stored.

     code: nil
     stacktrace:
       (propcheck 1.4.1-dev) lib/properties.ex:244: PropCheck.Properties.handle_check_results/2
       test/bla_test.exs:5: (test)



Finished in 0.09 seconds (0.00s async, 0.09s sync)
1 property, 1 failure

Randomized with seed 504774
[1]    350739 exit 1     mix test


  1) property biggest num test (BlaTest)
     test/bla_test.exs:5
     Property Elixir.BlaTest.property biggest num test() failed. Counter-Example is:


     Consider running `MIX_ENV=test mix propcheck.clean` if a bug in a generator was
     identified and fixed. PropCheck cannot identify changes to generators. See
     https://github.com/alfert/propcheck/issues/30 for more details.

     code: nil
     stacktrace:
       (propcheck 1.4.1-dev) lib/properties.ex:260: PropCheck.Properties.handle_check_results/2
       test/bla_test.exs:5: (test)



Finished in 0.09 seconds (0.00s async, 0.09s sync)
1 property, 1 failure

Randomized with seed 317928
```

The message `Consider running ..` only happens if a persisted counter example is used again. So my theory is that PropCheck fails to print the counter example `[]` correctly.

**Comment by evnu** [comment]
@alfert `counter_example_inspect/1` interprets `[]` as `:commands`, but it should be `:data` in this case.
