### ISSUE TITLE
(UndefinedFunctionError) function :eunit_lib.fun_parent/1 is undefined or private

### ISSUE THREAD

**Issue by coop** [alfert/propcheck#217]
Hi,

I have a very trivial test that fails with:

```
** (UndefinedFunctionError) function :eunit_lib.fun_parent/1 is undefined or private
```

The test looks like:

```elixir
defmodule App.PropertyTest do
  use ExUnit.Case, async: false

  use PropCheck
  use PropCheck.StateM

  property "it works", [:verbose, {:numtests, 100}] do
    forall cmds <- commands(__MODULE__) do
      {history, state, result} = run_commands(__MODULE__, cmds)

      (result == :ok)
      |> aggregate(command_names(cmds))
      |> when_fail(print_report({history, state, result}, cmds))
    end
  end

  def initial_state do
    %{}
  end

  def command(_state) do
    []
  end

  def precondition(_, _) do
    false
  end
end
```

Is there something I need to setup that I haven't?

**Comment by alfert** [comment]
Hi @coop , 

not sure what you wanna do, but if the `precondition` for command execution is always `false` and there are no commands to generate (ie. empty list), then PropCheck and the under PropEr has a hard time to do anything useful (= generating command sequences and executing them if all preconditions are satisfied). 

Please try out a more useful example and see if the bug still occurs. You can examples for that in test directory of PropCheck (e.g. https://github.com/alfert/propcheck/blob/master/test/master_statem_test.exs) 

The referenced missing function comes from the underlying Erlang standard library. That feels weird. But w/o information about your setup (OS, Elixir, PropCheck, Proper, and Erlang versions as minimum) it is difficult to reason about your case (except that your property test is not useful).

**Comment by coop** [comment]
@alfert

>it is difficult to reason about your case (except that your property test is not useful)

I was simplifying my property down to the minimum reproducible test case to demonstrate the error. I came across this error while writing a stateful property test for my system where I'd written an incorrect set of commands and preconditions where nothing matched - this error was incredibly hard to track down so I thought I'd raise the issue and see if a more informative error could be raised.

OS Mac 13.2.1
Erlang 25.2.2
Elixir 1.14.3
PropCheck 1.4.1
Proper 1.4.0

I have no experience with eunit so I'm not sure where to start looking.

**Comment by alfert** [comment]
Ah, that explains a lot. Just for reference: `eunit` is the Erlang unit testing framework which is stable for a decade or so. 

It is a good idea to at least document it. The trivial case of returning an empty list of commands should be testable, but the general case depends on the interaction of preconditions and commands. Difficult to act upon, e.g. if your commands function returns anything, but the precondition is always false. But I agree that the error message/exception is wrong. Feels like something that requires attention in Proper. 

Do you have a stack trace at hand?

**Comment by coop** [comment]
@alfert here is an example when I suspect proper thinks it cannot generate a valid command (inferred by `:proper_statem.commands_gen/4`):

```
** (UndefinedFunctionError) function :eunit_lib.fun_parent/1 is undefined or private
     stacktrace:
       :eunit_lib.fun_parent(#Function<52.1463473/1 in :proper_statem.commands_gen/4>)
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:176: :proper_gen."-generate/3-lc$^0/1-0-"/1
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:176: :proper_gen.generate/3
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:136: :proper_gen.generate/1
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:186: :proper_gen.generate/3
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:136: :proper_gen.generate/1
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:198: :proper_gen.generate/3
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:136: :proper_gen.generate/1
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:200: :proper_gen.generate/3
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:136: :proper_gen.generate/1
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:186: :proper_gen.generate/3
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:136: :proper_gen.generate/1
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:193: :proper_gen.generate/3
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:136: :proper_gen.generate/1
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:198: :proper_gen.generate/3
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:136: :proper_gen.generate/1
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:200: :proper_gen.generate/3
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:136: :proper_gen.generate/1
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:186: :proper_gen.generate/3
       (proper 1.4.0) /Users/dad/Code/youtooz/vend/vend-firmware/fw/deps/proper/src/proper_gen.erl:136: :proper_gen.generate/1
```

I have no idea what is causing this, I'm trying to track it down.

**Comment by alfert** [comment]
Thank you for the stack trace!

**Comment by coop** [comment]
@alfert that stacktrace was because my preconditions failed and therefore there was no valid command to run.

**Comment by erszcz** [comment]
See https://github.com/proper-testing/proper/pull/291. The function was removed in OTP 25, but Proper has adopted a fix. Maybe a Proper version bump in Propcheck is due?

**Comment by evnu** [comment]
PropEr seems to be very inactive w.r.t. releasing these days. Maybe we should reference a commit instead.
