### ISSUE TITLE
1.4.2 not available on hex.pm

### ISSUE THREAD

**Issue by flambard** [alfert/propcheck#228]
Hi, and thanks for making propcheck!

I see that propcheck was bumped to version 1.4.2 a few months ago. Do you plan to make the new version available on hex.pm as well?

**Comment by evnu** [comment]
See https://github.com/alfert/propcheck/pull/226, we are currently blocked on releasing a new version of `PropCheck` as we need fixes from `PropEr` which are not released on hex.pm yet :-/

**Comment by flambard** [comment]
Oh, I see. :-/ Looks like I will have to use git references instead.
