### ISSUE TITLE
Handle basic non-recursive type constructors

### ISSUE THREAD

**Issue by alfert** [alfert/propcheck#3]
- unions
- ordinary ranges
- tuples
- maps

**Comment by evnu** [comment]
To put this into perspective, is this issue meant to adress missing type generators to create a type from a `@type` spec?

**Comment by alfert** [comment]
Yes, exactly. In particular maps are missing. But differences between the syntax of type expressions of Elixir vs. Erlang are also a problem, since at some point PropEr works on the literal strings of type expressions and assumes an Erlang syntax. My understanding was that this requires to re-implement a whole bunch of PropEr, which is quite complicated inside. This was the reason to stop this endeavour and create this issue as an reminder.

**Comment by alfert** [comment]
Won't fix - auto-generators are now remove from the source code base.
