### ISSUE TITLE
Handling PropEr:quickcheck/2 error values

### ISSUE THREAD

**Issue by evnu** [alfert/propcheck#36]
Currently, `{:error, }` from `PropEr:quickcheck/2` is considered a counterexample (#10) by PropCheck. This leads to unexpected behaviour.

For example, re-running a property after it failed due to `:cant_generate` ends with an unhelpful `:non_boolean_result` message. Consider the following example:

```elixir
defmodule FailingTest do
  use ExUnit.Case
  use PropCheck

  property "failing" do
    gen = such_that b <- false, when: b # will produce {:error, :cant_generate}
    forall b <- gen do
      b
    end
  end
end
```

First run ends as expected:

```
  1) property failing (FailingTest)
     test/failing_test.exs:5
     Property Elixir.FailingTest.property failing() failed. Counter-Example is:
     {:error, :cant_generate}
     
     code: nil
     stacktrace:
       (propcheck) lib/properties.ex:109: PropCheck.Properties.handle_check_results/3
       test/failing_test.exs:5: (test)
```

The second run, OTOH, ends with `:non_boolean_result`:

```
  1) property failing (FailingTest)
     test/failing_test.exs:5
     Property Elixir.FailingTest.property failing() failed. Counter-Example is:
     {:error, :non_boolean_result}
     
     code: nil
     stacktrace:
       (propcheck) lib/properties.ex:109: PropCheck.Properties.handle_check_results/3
       test/failing_test.exs:5: (test)
```

Re-running the property can only be done by removing the counterexamples file, which is suboptimal.

The error handling in https://github.com/alfert/propcheck/blob/master/lib/properties.ex#L107 must be improved. I think this should be `counterexample when is_list(counterexample)`.

In a similar fashion, https://github.com/alfert/propcheck/blob/master/lib/properties.ex#L106 might not do what is expected. `should_fail` should probably still output in error if no type instances were generated.

@alfert I can come up with a PR, if you are interested.

**Comment by evnu** [comment]
See also #28, were this behaviour was observed by @pallix.

**Comment by alfert** [comment]
👍 
I am away for the next week or so. So, take your time. I will gladly accept your PR.
