### ISSUE TITLE
Export formatting rules to work well with mix format

### ISSUE THREAD

**Issue by asd1o2487c** [alfert/propcheck#42]
Like described here https://hexdocs.pm/mix/master/Mix.Tasks.Format.html#module-importing-dependencies-configuration

For all the macros? I can do it, if you want.

**Comment by alfert** [comment]
Hmm. I am reluctant to add support for Elixir 1.7 when it is still in dev. How stable is this feature? And why should we do this, are there any relevant formatter we import? (Hint: I have no experience with Elixir's formatter, so I may say something stupid).

**Comment by asd1o2487c** [comment]
I think elixir formatter ships with Elixir 1.6. And, at least I think, it can improve some strange formatting I'm getting sometimes when I run it on files that use `propcheck`'s macros in it.

**Comment by asd1o2487c** [comment]
Funny thing though, now I don't get any strange formatting. I wanted to show you.

**Comment by asd1o2487c** [comment]
Ah, here

This
```elixir
  property "natural numbers are non-negative" do
    quickcheck forall n <- nat() do
      n >= 1
    end
  end
```
gets formatted into this
```elixir
  property "natural numbers are non-negative" do
    quickcheck forall(n <- nat()) do
      n >= 1
    end
  end
```

**Comment by alfert** [comment]
What happens when you remove the superfluous `quickcheck`?

Von unterwegs  gesendet

**Comment by asd1o2487c** [comment]
It gets formatted correctly.

```elixir
  property "natural numbers are non-negative" do
            forall n <- nat() do
          n >= 1
    

    end
  end
```
turns into
```elixir
  property "natural numbers are non-negative" do
    forall n <- nat() do
      n >= 1
    end
```

**Comment by asd1o2487c** [comment]
Indeed, maybe it's not really needed, I'll reopen this issue if I notice any more strangeness, but without `quickcheck` macro.
