### ISSUE TITLE
Does propcheck support symbolic call generators?

### ISSUE THREAD

**Issue by mmmries** [alfert/propcheck#50]
🎈 🎉 💙 💛 💚 🎈 🎉 💙 💛 💚 🎈 🎉 💙 💛 💚 🎈 🎉 💙 💛 💚 
Many thanks for making this awesome library. It has been very helpful to me so far 

I've been following along with propertesting.com and when I got to the section on [data generators using symbolic calls](http://propertesting.com/book_custom_generators.html#_symbolic_calls) I got stuck. I tried converting the examples into Elixir and then tried searching through hexdocs and the code in this repo, but I haven't found anything related to symbolic calls in data generators. It also wasn't mentioned in the [what is not available](https://github.com/alfert/propcheck/tree/5db632acce30202e3319c1a786521f443e344c17#what-is-not-available) section of the README in this project so maybe I'm just missing something?

I would be happy to help out with adding support or documenting support for this feature if you want to have it in this project.

**Comment by alfert** [comment]
I never tried these generators before, to be honest. But these calls simply standard generators which are evaluated by `proper`. I added a test showing that on `master`. Here is the example code translating Fred's example to Elixir: 

```elixir
def dict_autosymb(), do:
    sized(size, dict_autosymb(size, {:"$call", :dict, :new, []}))
  def dict_autosymb(0, dict), do: dict
  def dict_autosymb(n, dict), do:
    dict_autosymb(n-1, {:"$call", :dict, :store, [integer(), integer(), dict]})

  property "symbolic auto calls on dict - expected to fail" do
    forall d <- dict_autosymb() do
      :dict.size(d) < 5
    end
    |> fails
  end
```

Similar generators are used for property testing state-based systems. So, thanks for this hint, which is useful for my current work on overhauling this area in PropCheck by defining a nicer Elixirish DSL.
