### ISSUE TITLE
Enable usage of alternative Quickcheck implementations

### ISSUE THREAD

**Issue by alfert** [alfert/propcheck#7]
Since Quviqs Quickcheck has a commercial license, Proper is GPL, and Triq uses Apache, it seems to be helpful if we could support all of these 3 under the same Elixir interface so that the user can decide which library is currently used (as you can choose which markdown implementation you use for ex_doc).

**Comment by evnu** [comment]
@alfert Do you think this is still useful? Do the other implementations besides Quviq implement targeted property based testing?

**Comment by devstopfix** [comment]
I am happy to try implementing a `triq` interface - I really enjoyed using it when it was wrapped with `ExCheck`

**Comment by alfert** [comment]
Will never implement that, since all these libraries (and nowadays also including StreamData) have too small common footprint.
