### ISSUE TITLE
FunctionClauseError when running parallel tests

### ISSUE THREAD

**Issue by oltarasenko** [alfert/propcheck#79]
Hi,
I am getting the following error:

> rm _build/propcheck.ctex && mix test test/some_test.exs
> warning: variable "call" is unused
>   test/some_test.exs:70
> 
> 
> 
>   1) property stateful property (SomeTest)
>      test/some_test.exs:38
>      ** (FunctionClauseError) no function clause matching in anonymous fn/1 in :proper_types.weighted_union/1
> 
>      The following arguments were given to anonymous fn/1 in :proper_types.weighted_union/1:
> 
>          # 1
>          {3, :call, Registry, :put_meta, [Test, {:"$type", [generator: &:proper_gen.atom_gen/1, reverse_gen: &:proper_gen.atom_rev/1, size_transform: #Function<19.71592878/1 in :proper_types.atom/0>, is_instance: #Function<20.71592878/1 in :proper_types.atom/0>, kind: :wrapper]}, {:"$type", [parts_type: {:"$type", [generator: {:typed, #Function<27.71592878/2 in :proper_types.list/1>}, is_instance: {:typed, #Function<28.71592878/2 in :proper_types.list/1>}, internal_type: {:"$type", [env: ["$type": [env: 65, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 66, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 67, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 68, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 69, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 70, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 71, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 72, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 73, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 74, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 75, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 76, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic], "$type": [env: 77, generator: {:typed, #Function<104.71592878/1 in :proper_types.exactly/1>}, is_instance: {:typed, #Function<105.71592878/2 in :proper_types.exactly/1>}, kind: :basic]], generator: {:typed, #Function<41.71592878/1 in :proper_types.union/1>}, is_instance: {:typed, #Function<42.71592878/2 in :proper_types.union/1>}, shrinkers: [#Function<44.71592878/3 in :proper_types.union/1>, #Function<43.71592878/3 in :proper_types.union/1>], kind: :basic]}, get_length: &:erlang.length/1, split: &:lists.split/2, join: &:lists.append/2, get_indices: #Function<29.71592878/2 in :proper_types.list/1>, remove: &:proper_arith.list_remove/2, retrieve: &:lists.nth/2, update: &:proper_arith.list_update/3, kind: :container]}, combine: #Function<0.123162187/1 in SomeTest.key/0>, shrink_to_parts: false, kind: :constructed]}]}
> 
>      stacktrace:
>        (proper) src/proper_types.erl:886: anonymous fn/1 in :proper_types.weighted_union/1
>        (stdlib) lists.erl:1239: :lists.map/2
>        (proper) src/proper_types.erl:887: :proper_types.weighted_union/1
>        (proper) src/proper_statem.erl:342: anonymous fn/4 in :proper_statem.commands/4
>        (proper) src/proper_gen.erl:187: :proper_gen.generate/3
>        (proper) src/proper_gen.erl:127: :proper_gen.generate/1
>        (proper) src/proper_gen.erl:189: :proper_gen.generate/3
>        (proper) src/proper_gen.erl:127: :proper_gen.generate/1
>        (proper) src/proper_gen.erl:175: :proper_gen.generate/3
>        (proper) src/proper_gen.erl:127: :proper_gen.generate/1
>        (proper) src/proper_gen.erl:182: :proper_gen.generate/3
>        (proper) src/proper_gen.erl:127: :proper_gen.generate/1
>        (proper) src/proper_gen.erl:175: :proper_gen.generate/3
>        (proper) src/proper_gen.erl:127: :proper_gen.generate/1
>        (proper) src/proper_gen.erl:175: :proper_gen.generate/3
>        (proper) src/proper_gen.erl:127: :proper_gen.generate/1
>        (proper) src/proper_gen.erl:175: :proper_gen.generate/3
>        (proper) src/proper_gen.erl:127: :proper_gen.generate/1
>        (proper) src/proper_gen.erl:114: :proper_gen.safe_generate/1
>        (proper) src/proper.erl:1400: :proper.run/3
> 
> 
> 
> Finished in 0.06 seconds
> 1 property, 1 failure

For the following test case:
```defmodule SomeTest do
  use ExUnit.Case
  use PropCheck
  use PropCheck.StateM

  require Logger

  def key() do
    let chars <- list(elements('ABCDEFGHIJKLM')) do
      to_string(chars)
    end
  end

  def limited_key() do
    let item <- elements(Enum.map(1..10, fn x -> "KEY_#{x}" end)) do
      item
    end
  end

  def name() do
    oneof([non_empty(limited_key())])
  end

  defp stop_process(pid) do
    Process.monitor(pid)
    Process.unlink(pid)
    Process.exit(pid, :shutdown)

    receive do
      {:DOWN, _, :process, _pid, _reason} ->
        :ok

      msg ->
        IO.inspect(msg)
    end
  end

  property "stateful property", [:verbose, numtests: 100] do
    forall cmds <- parallel_commands(__MODULE__) do
      {:ok, pid} = Registry.start_link(keys: :unique, name: Test)
      {history, state, result} = run_parallel_commands(__MODULE__, cmds)
      stop_process(pid)

      (result == :ok)
      |> aggregate(command_names(cmds))
      |> when_fail(
        IO.puts("""
        History: #{inspect(history)}
        State: #{inspect(state)}
        Result: #{inspect(result)}
        """)
      )
    end
  end

  def initial_state(), do: %{}

  def command(_state) do
    frequency([
      {3, :call, Registry, :put_meta, [Test, atom(), key()]}
    ])
  end

  def precondition(_state, {:call, _mod, _fun, _args}), do: true

  def postcondition(_state, {:call, _mod, _fun, _args}, _res) do
    true
  end

  def next_state(state, _res, call) do
    state
  end
end
```

Do I have some configuration problem? Or it's something with the test itself?

**Comment by evnu** [comment]
> `{3, :call, Registry, :put_meta, [Test, atom(), key()]}`

`frequency` (or `weighted_union`, which is called further down the chain) expects the elements in the form `{frequency(), generator()}`. So this should probably be 

```elixir
{3, {:call, Registry, :put_meta, [Test, atom(), key()]}}
```

For your example, the following would work (while not doing something particularly useful):

```elixir
  def command(_state) do
    frequency([
      {3, {:call, Registry, :put_meta, [Test, atom(), key()]}}
    ])
  end

  def precondition(_state, _), do: true

  def postcondition(_state, _, _res) do
    true
  end

  def next_state(state, _res, call) do
    state
  end
```

If you want to check if the function call actually happens, print the result `_res` in `postcondition/3`.

**Comment by oltarasenko** [comment]
Thanks, @evnu!
