### ISSUE TITLE
Bug in level test?

### ISSUE THREAD

**Issue by evnu** [alfert/propcheck#82]
As can be seen in the [tests of PropCheck](https://github.com/alfert/propcheck/commit/4af8b8804874e855c7124679ac56d081bb0aadf1#diff-f0234345bd20e26cbfd8f03f6135a08fR36), we encounter a `{$used, _, _}` tuple with TPBT. I followed the [tutorial](http://proper.softlab.ntua.gr/Tutorials/PropEr_testing_with_search_strategies.html) to get a first glimpse into PropEr's TPBT, where I stumbled over this as well. It seems unclear how to correctly interpret this internal data. In PropCheck's test, the interpretation seems to be `{:"$used", old, new}`. I think that the interpretation should be `{:"$used", new, old}`.

In my implementation, I only generate a single additional step for each invocation of `path_next_sa()`:

```elixir
  def path_next_sa() do
    fn
      old_path, _temperature when is_list(old_path) ->
        let next_step <- step() do
          old_path ++ [next_step]
        end

      {:"$used", _new_step, old_path}, _temperature when is_list(old_path) ->
        let next_step <- step() do
          old_path ++ [next_step]
        end
    end
  end
```

If I adapt PropCheck's test to also generate a single new step, while maintaining that the old path is the second tuple element, this fails.

```elixir
  def path_next_sa() do
    fn
      old_path, _temperature when is_list(old_path) ->
        let next_step <- step() do
          old_path ++ [next_step]
        end

      {:"$used", old_path, _next_step}, _temperature when is_list(old_path) ->
        let next_step <- step() do
          old_path ++ [next_step]
        end
    end
  end
```

Error:

```
** (FunctionClauseError) no function clause matching in anonymous fn/2 in MazeGameTest.path_next/0

     The following arguments were given to anonymous fn/2 in MazeGameTest.path_next/0:
     
         # 1
         {:"$used", :down, [:right, :down]}
     
         # 2
         1.0
```

**Comment by alfert** [comment]
Hmm, I am puzzled, to be honest. My implementation in `level_tpbt.exs` works (but only on my machine and not on travis which I do not understand - but this is a different story). 

```elixir
def path_next_sa() do
    fn
      (prev_path, _temperature) when is_list(prev_path) ->
          let next_steps <- vector(20, step()), do:
            prev_path ++ next_steps
      ({:"$used",  prev_path, _another_path}, _temperature) when is_list(prev_path) ->
       let next_steps <- vector(20, step()), do:
          prev_path ++ next_steps
    end
  end
```
If I change the `vector(20, step())?` to a simple `step()` and put the result in a singleton list, I get the same error as you. Changing the order of `prev_path` and `_another_path` seems to help, indeed. 

Independent that the `forall_sa` approach is only available for compatibility to the tutorial and the scientific paper, we should change this.

**Comment by evnu** [comment]
> Hmm, I am puzzled, to be honest.

Yes, this is puzzling indeed. Interestingly, the level [example](https://github.com/proper-testing/proper/blob/master/examples/level.erl#L170) in PropEr does not need to handle `":$used`. I did not yet find the location where the internal structure is dropped to the instance itself. There are some references to `":$used`, but I could not make sense of it yet.

**Comment by evnu** [comment]
I see this exact error on my other machine with Elixir v1.7.

This might be related to `proper_sa:init_target/1` (which makes use of the `gen` key):

```erlang
init_target(#{gen := Gen}) ->
  init_target(proper_gen_next:from_proper_generator(Gen));
init_target(#{first := First, next := Next}) ->
  create_target(#sa_target{first = First, next = Next}).
```

This function is in turn called by `proper_target:get_target/2`:

```erlang
get_target(Key, Opts) ->
  Strategy = strategy(),
  case Strategy:retrieve_target(Key) of
    undefined ->
      FreshTarget = Strategy:init_target(Opts),
      Strategy:store_target(Key, FreshTarget),
      FreshTarget;
    StoredTarget ->
      StoredTarget
  end.
```

`proper_target:get_target/2` is called by `proper_target:targeted_gen/2`:

```erlang
targeted_gen(Key, TMap) ->
  {State, NextFunc, _FitnessFunc} = get_target(Key, TMap),
  {NewState, NextValue} = NextFunc(State),
  update_target(Key, NewState),
  NextValue.
```

And here we finally arrive at `proper_target:targeted/2` (AKA `?TARGET`):

```erlang
targeted(Key, TMap) ->
  ?SHRINK(proper_types:exactly(?LAZY(targeted_gen(Key, TMap))),
          [get_shrinker(TMap)]).
```

I think `TMap` should already contain the `:gen` at this point. Note that `get_shrinker(TMap)` here is wrapped in `?DELAY` by `?SHRINK`, so this does not crash until the shrinker is actually to be used (in case that the shrinker cannot be found).

**Comment by alfert** [comment]
Ok, that explains why the map of type `TMap` has keys `:first` and `:next` and is the parameter. But function `get_shrinker` expects the key `:gen` in `TMap` and there is no source line where the key `:gen` is set. At least my search with grep does not succeed. 

And what irritates me most is that it works in Elixir 1.8, 1.6 and 1.5 but not in Elixir 1.7. All running the same OTP Version 20.

**Comment by evnu** [comment]
> All running the same OTP Version 20.

I am running Elixir v1.7 with OTP 21 and still encounter this error:

```
$ elixir --version
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.7.4 (compiled with Erlang/OTP 21)
```

**Comment by evnu** [comment]
> there is no source line where the key `:gen` is set.

The only occurrence I could find is in [`proper.erl` on line 992](https://github.com/proper-testing/proper/blob/master/src/proper.erl#L992):

```erlang
%% @private
-spec exists(proper_types:raw_type(), dependent_test(), boolean()) -> exists_clause().
exists(RawType, DTest, Not) ->
    {exists, #{gen => RawType}, DTest, Not}.
```

Found with ripgrep and PropEr as of e3bf535:

```
$ rg "gen =" src
src/proper.erl           
992:    {exists, #{gen => RawType}, DTest, Not}.
```

**Comment by evnu** [comment]
If I replace `forall_sa` with `forall_targeted` in the property, `:gen` is indeed added:

```
{:exists,
 %{
   gen: {:"$type",
    [
      generator: #Function<0.65787913/0 in :proper_target.targeted/2>,
      alt_gens: #Function<1.65787913/0 in :proper_target.targeted/2>,
      kind: :wrapper
    ]}
 }, #Function<2.44557854/1 in MazeGameTest.prop_exit_unreachable/1>, true}
```

The test then fails with an error in `:proper_gen_next.replace_generators/1`:

```
1) property level 0 reachable (MazeGameTest)
     test/maze_game_test.exs:7
     ** (CaseClauseError) no case clause matching: :undefined
     code: property "level 0 reachable", [:verbose] do
     stacktrace:
       (proper) src/proper_gen_next.erl:156: :proper_gen_next.replace_generators/1
       (proper) src/proper_gen_next.erl:809: anonymous fn/3 in :proper_gen_next.wrapper_gen_sa/1
       (proper) src/proper_gen_next.erl:198: :proper_gen_next.restrict_generation/6
       (proper) src/proper_sa.erl:227: :proper_sa.next_func/1
       (proper) src/proper_target.erl:117: :proper_target.targeted_gen/2
       (proper) src/proper_gen.erl:187: :proper_gen.generate/3
       (proper) src/proper_gen.erl:127: :proper_gen.generate/1
       (proper) src/proper_gen.erl:189: :proper_gen.generate/3
       (proper) src/proper_gen.erl:127: :proper_gen.generate/1
       (proper) src/proper_gen.erl:189: :proper_gen.generate/3
       (proper) src/proper_gen.erl:127: :proper_gen.generate/1
       (proper) src/proper_gen.erl:114: :proper_gen.safe_generate/1
       (proper) src/proper.erl:1287: :proper.perform_search/8
       (proper) src/proper.erl:1366: :proper.run/3
       (proper) src/proper.erl:1244: :proper.perform/7
       (proper) src/proper.erl:1120: :proper.inner_test/2
       (proper) src/proper.erl:1111: :proper.test/2
       (propcheck) lib/properties.ex:87: PropCheck.Properties.execute_property/3
       test/maze_game_test.exs:7: (test)
```

I guess that the strategy is not correctly set?

**Comment by alfert** [comment]
and the tour is going on: A little change of adding Logger output and calling the `forall` function via its macro definition not results in out-of-memory bug in 1.8 and a failure in 1.6, but in runs in 1.5 and 1.7 on travis. On my local machine, everything is still fine with 1.8.0. 

This feels fishy, like a small yet stupid bug that renders the entire system unreliable.

**Comment by evnu** [comment]
@alfert Do you refer to 609181a w.r.t. debugging output?

**Comment by evnu** [comment]
I have the impression that we should not use `forall_sa` and other such macros at all, including `target`. From `proper_target.erl`:

```erlang
%%% To use TPBT the test specification macros `?FORALL_TARGETED`, `?EXISTS',
%%% and `?NOT_EXISTS' are used.
```
And in `include/proper_common.hrl`, the macros `TARGET`, `STRATEGY` and `FORALL_SA` are also listed for backwards compatibility:

```erlang
%%------------------------------------------------------------------------------
%% Macros for backwards compatibility
%%------------------------------------------------------------------------------
-define(TARGET(TMap), proper_target:targeted(make_ref(), TMap)).
-define(STRATEGY(Strat, Prop), ?SETUP(fun (Opts) ->
                                          proper_target:use_strategy(Strat, Opts),
                                          fun proper_target:cleanup_strategy/0
                                      end, Prop)).
-define(FORALL_SA(X, RawType, Prop),
        ?STRATEGY(proper_sa, proper:forall(RawType,fun(X) -> Prop end))).
```

I was able to remove the `:"$used"` case in the NF when I used `forall_targeted`.

**Comment by evnu** [comment]
See, #86. By avoiding the legacy macros altogether, `:"$used" does not occur anymore, making the original problem of how to interpret `old` and `new` obsolete! I believe the right way to handle all this is to remove the backwards compatibility macros and only add a description in the documentation on how to translate that into the new form. One more todo would be to make `collect/1` work within `forall_targeted`, but this is outside of the scope of this issue here.

**Comment by alfert** [comment]
`collect/1` does not work with targeted PBT. This is a design decision within proper and would be a good reason to implement our own version of TPBT. At least I would like to see how my search space is affected by `forall_targeted` and `exists`. 

With #86 in place, we can close this issue.
