### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by evnu** [alfert/propcheck#96]
It seems that travis is no longer called when pull requests are submitted. Can this be fixed?

**Comment by alfert** [comment]
I recognized this as well, but I have no clue. My assumption is that this has something to do with the move of travis towards their new services. It is annoying.

**Comment by evnu** [comment]
Apparently, travis still builds successfully on my branches (see [this](https://github.com/alfert/propcheck/pull/94#issuecomment-474110004) for example). Maybe the settings for the repository must be adapted?

**Comment by evnu** [comment]
Maybe [this](https://github.com/travis-ci/travis-ci/issues/9440) issue on travis-ci can provide some hints on what to try.

**Comment by evnu** [comment]
@alfert We could also give circleci a try.

**Comment by evnu** [comment]
In #106:

> Apparently, circleci did not run for that pull request.

@alfert I believe there is some configuration to be done here. It seems that circleci is only building if somebody with a circleci account and PropCheck as a registered project triggers a build. Can you check if you have the following option set for PropCheck:

Settings > Advanced Settings > Build Forked Pull Requests

**Comment by alfert** [comment]
Thanks for the hint. I changed the settings in CircleCI.
